language: c

os:
  - linux
  - osx

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_uv.sh
  #- sudo luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - git submodule update --init --recursive
  - git submodule update --recursive

install: 
  - sudo luarocks make rockspecs/openssl-scm-1.rockspec

script: 
  - cd test
  - curl https://raw.githubusercontent.com/bluebird75/luaunit/master/luaunit.lua > luaunit.lua
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
